### ISSUE TITLE
daily-poem模块报错

### ISSUE THREAD

**Issue by CECoffee** [Yucklys/polybar-nord-theme#1]
>$ sh .config/polybar/launch.sh
Bars launched...
error: Disabling module "daily-poem" (reason: Inter-process messaging needs to be enabled)
 >$

**Comment by Yucklys** [comment]
![polybar-nord issue_1.png](https://tupp.xyz/2019/08/13/15656705085d523c6ce011f.png)
在 `config` 文件中的[bar/nord-down]下，看一下 `enable-ipc` 是否为 `true`

**Comment by CECoffee** [comment]
> ![polybar-nord issue_1.png](https://camo.githubusercontent.com/41e567ea84a3f59f30b7a8090aea3c53e67d1606/68747470733a2f2f747570702e78797a2f323031392f30382f31332f31353635363730353038356435323363366365303131662e706e67)
> 在 `config` 文件中的[bar/nord-down]下，看一下 `enable-ipc` 是否为 `true`

问题解决，谢大佬！
