### ISSUE TITLE
突然之间，不能显示图标了。

### ISSUE THREAD

**Issue by vvlaw** [Yucklys/polybar-nord-theme#12]
一直都是好好的，仅仅是更新系统。
<a href="https://ibb.co/VHn3hW8"><img src="https://i.ibb.co/6v9NpR5/2022-02-12-21-07.png" alt="2022-02-12-21-07" border="0"></a>

**Comment by Yucklys** [comment]
If you are using arch, the `ttf-font-awesome` package is updated to V6.0 which can not be recognized by the old config.
I have merged pull request #11 so it should be able to work with FontAwesome6 now. Just pull the latest commit and try again.

**Comment by vvlaw** [comment]
Yes. It worked! Thank you very much.
