### ISSUE TITLE
Where is the wallpaper.

### ISSUE THREAD

**Issue by shahid777-py** [Yucklys/polybar-nord-theme#2]
It would a great help if u provide the wallpaper with that.

**Comment by Yucklys** [comment]
I added the 3840x2160 version of the wallpaper to the repository. If you are interested in other size, [here](https://www.reddit.com/r/wallpapers/comments/aa1oz1/beautiful_mountains_and_clouds_3840x2160/) is where I get the picture from.

**Comment by shahid777-py** [comment]
Thanks
