### ISSUE TITLE
error: Disabling module "daily-poem" (reason: Inter-process messaging needs to be enabled)

### ISSUE THREAD

**Issue by crisqyxw** [Yucklys/polybar-nord-theme#3]
error: Disabling module "daily-poem" (reason: Inter-process messaging needs to be enabled)

**Comment by Yucklys** [comment]
Check the `[bar/nord-down]` block inside `light-config` or `dark-config`, depends on which theme you choose. There should be a line `enable-ipc = true`. If not, add this line and try again.
