### ISSUE TITLE
backlight module: wrong type definition for intel cards

### ISSUE THREAD

**Issue by ghost** [Yucklys/polybar-nord-theme#8]
for people having an intel graphics card or a hybrid the backlight is controlled by the intel_backlight module located at  /sys/class/backlight/intel_backlight/

fix : 

[module/backlight]
type = internal/backlight
card = intel_backlight  #replaced xbacklight to intel_backlight
enable-scroll = true
![Screenshot from 2022-01-09 20-22-56](https://user-images.githubusercontent.com/66838685/148687999-472f090e-e9fd-410e-a694-dbc4fbecffa7.png)

**Comment by Yucklys** [comment]
Use xbacklight as default in the latest commit. User can switch back to backlight by removing the comments in `nord-top`.
